instance_create(x, y, obj_inventory);
instance_create(x, y, obj_player);
instance_create(x, y, dgen);
ini_open("save.dat");
obj_player.x = ini_read_real("Player Values", "x", 0);
obj_player.y = ini_read_real("Player Values", "y", 0);
global.toughness = ini_read_real("Player Values", "floor", 1);
global.class = ini_read_string("Player Values", "class", "none");
obj_player.class = ini_read_string("Player Values", "class", "none");
obj_player.turn = ini_read_real("Player Values", "turn", 0);
ini_close();
file_delete("save.dat");
